name: Publish To Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    permissions:
      pages: write      
      id-token: write   
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Build Site
        run: emacs -Q --script build-site.el
        

      - name: Deploy to GitHub Pages
        id: deployment
        uses: avinal/github-pages-deploy-action@v0.9
